package main

import (
	"bufio"
	"errors"
	"flag"
	"io"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"time"

	"github.com/524D/filelist2db/dataprovider"
	"github.com/524D/filelist2db/dataprovidersqlite"
	_ "modernc.org/sqlite"
)

type Args struct {
	dbFile string
}

var args Args

type timeBin struct {
	maxAgeS uint64 // Maximum age in seconds
	txt     string // Textual description of time bin
}

var timeBins = [...]timeBin{
	{(3600 * 24 * 30), "< 1 month"},
	{(3600 * 24 * 90), "1 to 3 months"},
	{(3600 * 24 * 365), "3 to 12 months "},
	{(3600 * 24 * 365 * 3), "1 to 3 years"},
	{(3600 * 24 * 365 * 5), "3-5 years"},
	{(3600 * 24 * 30) * 999, "> 5 years"},
}

func parseCmdLine() []string {
	// Parse command line arguments
	// -db <database>: name of sqlite database to use (default: "db.sqlite")
	// Remaining arguments: file lists to process

	// If no arguments, print usage and exit
	// If -h or --help, print usage and exit

	flag.StringVar(&args.dbFile, "db", "db.sqlite", "name of sqlite database to use")
	flag.Parse()
	return flag.Args()
}

// Decode computer name, base path and search timestamp from filename of "find" result
// The filename should be named like:
// [_computername_]<escaped_base_path>_<timestamp>.<txt|lst>
// Where:
//   - computername is the name of the computer whose files are indexed. Can
//     be absent if the filepath refers to a network share
//   - escaped_base_path is the path under which the file info is obtained
//   - timestamp is the timestamp of the scan, in the format YYYYMMDD-HHMMSS
//
// Since the path name contains characters that cannot be part of a filename,
// it is escaped:
// A leading underscore ("_") is replaced by "%5F"
// Other invalid filename characters are replaced by "%" followed by their ASCII/UTF8
// hex character code, e.g. "%2F" for slash ("/") and "%5C" for backslash ("\").
// "%" is replaced by %25
func decodeFindFilename(fn string) (string, string, int64, error) {
	re := regexp.MustCompile(`^(?:.*[/\\])?(?:_([^/\\]*?)_)?([^/\\]*?)_([0-9\-]+)\.lst|\.txt$`)
	match := re.FindStringSubmatch(fn)
	if match == nil {
		return ``, ``, 0, errors.New("can't extract basepath/timestamp from filename")
	}
	basePath, err := url.QueryUnescape(match[2])
	if err != nil {
		return ``, ``, 0, errors.New("can't decode basepath from filename")
	}
	ts, err := time.Parse(`20060102-150405`, match[3])
	if err != nil {
		return ``, ``, 0, errors.New("can't decode timestamp from filename")
	}
	t := ts.Unix()

	return match[1], basePath, t, nil
}

func binTime(t int64, acqTime int64) int {
	age := acqTime - t
	for i, tb := range timeBins {
		if age < int64(tb.maxAgeS) {
			return i
		}
	}
	return len(timeBins) - 1
}

func sumSz(sz [len(timeBins)]uint64) uint64 {
	sum := uint64(0)
	for i := 0; i < len(timeBins); i++ {
		sum += sz[i]
	}
	return sum
}

func parseFileList(d dataprovider.DataProvider, reader io.Reader) error {
	// parseFileList parses a file list and adds the files to the data provider
	// File info e.g. generated by:
	// find ${DIR} -type f -printf '%s\t%U\t%i\t%n\t%T@\t%A@\t%C@\t%P\n'
	// Regex to parse file info. We discard fractional part of timestamp.
	re := regexp.MustCompile(`^([0-9]*)\t([0-9]*)\t([0-9]*)\t([0-9]*)\t([0-9]*)(?:\.[0-9]*)\t([0-9]*)(?:\.[0-9]*)\t([0-9]*)(?:\.[0-9]*)\t(.*)$`)

	scanner := bufio.NewScanner(reader)
	d.StartTransaction()
	for scanner.Scan() {
		l := scanner.Text()
		m := re.FindStringSubmatch(l)
		if m == nil || len(m) < 9 || m[8] == `` {
			// Parsing line failed
		} else {
			var f dataprovider.FileInfo
			f.Size, _ = strconv.ParseUint(m[1], 10, 64)
			uidNum, _ := strconv.ParseUint(m[2], 10, 64)
			f.Uid = dataprovider.UidT(uidNum)
			f.Mtime, _ = strconv.ParseInt(m[5], 10, 64)
			f.Atime, _ = strconv.ParseInt(m[6], 10, 64)
			f.Path = m[8]
			err := d.AddFile(f)
			if err != nil {
				return err
			}
		}
	}
	d.CommitTransaction()
	return nil
}

func processListFile(d dataprovider.DataProvider, fn string) error {
	computerName, basePath, acqTime, err := decodeFindFilename(fn)
	if err != nil {
		return err
	}
	d.SetSourceInfo(computerName, basePath, acqTime)
	f, err := os.Open(fn)
	if err != nil {
		return err
	}
	defer f.Close()

	return parseFileList(d, f)
}

func main() {
	// Parse command line arguments
	files := parseCmdLine()

	// Create data provider
	d, err := dataprovidersqlite.InitDataProviderSqlite(args.dbFile)
	if err != nil {
		panic(err)
	}
	defer d.Finalize()

	// Process files
	for _, fn := range files {
		err = processListFile(d, fn)
		if err != nil {
			panic(err)
		}
	}
}
